export const combos = [
  {
    number: 1,
    title: "Pollo Asada",
    price: "$10.22",
    img: "pollo_asado_600x416.jpg",
    fontSize: 32,
  },
  {
    number: 2,
    title: "Burrito & Taco",
    price: "$10.11",
    img: "burrito_and_taco_600x416.jpg",
    fontSize: 27,
  },
  {
    number: 3,
    title: "Two beef Tacos",
    price: "$10.11",
    img: "two_beef_tacos-600x416.jpg",
    fontSize: 24,
  },
  {
    number: 4,
    title: "Fajitas Chicken or Steak",
    price: "$12.68",
    img: "fajitas_chicken_or_steak_600x416.jpg",
    fontSize: 20,
  },
  {
    number: 5,
    title: "Two Enchiladas",
    price: "$9.37",
    img: "two_enchiladas_600x416.jpg",
    fontSize: 25,
  },
  {
    number: 6,
    title: "Camarones Rancheros",
    price: "$12.96",
    img: "camarones_rancheros_600x416.jpg",
    fontSize: 26,
  },
  {
    number: 7,
    title: "Tostada & Taco",
    price: "$10.11",
    img: "tostada_and_taco_600x416.jpg",
    fontSize: 30,
  },
  {
    number: 8,
    title: "4 Rolled Tacos With Guacamole",
    price: "$10.54",
    img: "4_rolled_tacos_with_guacomole_600x416.jpg",
    fontSize: 20,
  },
  {
    number: 9,
    title: "Carne Asada",
    price: "$13.17",
    img: "carne_asada_600x416.jpg",
    fontSize: 30,
  },
  {
    number: 10,
    title: "Two Chicken Tacos",
    price: "$10.11",
    img: "two_chicken_tacos_600x416.jpg",
    fontSize: 23,
  },
  {
    number: 11,
    title: "Green Chile",
    price: "$10.22",
    img: "green_chile_600x416.jpg",
    fontSize: 26,
  },
  {
    number: 12,
    title: "Adobada Plate",
    price: "$9.85",
    img: "adobada_plato_600x416.jpg",
    fontSize: 30,
  },
  {
    number: 13,
    title: "Chimichanga Plate",
    price: "$10.88",
    img: "chimichanga_plate_600x416.jpg",
    fontSize: 23,
  },
  {
    number: 14,
    title: "Two Carne Asada Burritos",
    price: "$15.13",
    img: "two_carne_asada_burritos_600x416.jpg",
    fontSize: 20,
  },
  {
    number: 15,
    title: "Carnitas Plate",
    price: "$10.58",
    img: "carnitas_plate_600x416.jpg",
    fontSize: 30,
  },
  {
    number: 16,
    title: "Two Fish Tacos",
    price: "$9.97",
    img: "two_fish_tacos_600x416.jpg",
    fontSize: 33,
  },
  {
    number: 17,
    title: "Two Chiles Rellenos",
    price: "$10.51",
    img: "two_chiles_rellenos_600x416.jpg",
    fontSize: 28,
  },
  {
    number: 18,
    title: "Two Carne Asada Tacos",
    price: "$12.68",
    img: "two_carne_asada_tacos_600x416.jpg",
    fontSize: 23,
  },
  {
    number: 19,
    title: "Burrito & Enchilada",
    price: "$10.11",
    img: "burrito_and_enchilada_600x416.jpg",
    fontSize: 26,
  },
  {
    number: 20,
    title: "Taco & Enchilada",
    price: "$10.11",
    img: "taco_and_enchilada_600x416.jpg",
    fontSize: 28,
  },
]
